### PR TITLE
BUG - Sidebar Styling issue with Fieldset

### PR DESCRIPTION
**Pull request by reisandylamdjani**

### CODE REVIEW

**Comment by reisandylamdjani** [comment]
I've also changed one line for the discard change container, so I'll just add it to this PR

**Comment by reisandylamdjani** [comment]
I've pushed a lot of the styling bugs that I saw on the main branch for now just so we dont need multiple PR's and branches

**Review by Summerr12 — COMMENTED** [review]
the collapse looks good. Im not to sure what the tests are trying to error out though

**Review by Summerr12 — APPROVED** [review]

**Comment by azpi-arte** [comment]
I still see a few visual bugs, I'll try to get them patched up: dropdown icons are highlighted. Hovered journals are larger than static ones

(currently working on this)

**Comment by reisandylamdjani** [comment]
yeahh the hovered journal increases in size, not sure about that one

**Review by azpi-arte — APPROVED** [review]
Great changes.

**Pull request merged**
